=== Alexey1406/couchbase-mobile-portal/docs/src/docs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- === -->
	<!-- Set -->
	<!-- === -->
	
	<xs:element name="set">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="0" maxOccurs="1"/>
				
				<xs:element name="items" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="set"/>
							<xs:element ref="class"/>
							<xs:element ref="guide"/>
							<xs:element ref="page"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Class -->
	<!-- ===== -->
	
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="dependencies" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="lessons" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="lesson"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lesson">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="tasks" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="task">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
										<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									
									<xs:attribute name="id" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Guide -->
	<!-- ===== -->
	
	<xs:element name="guide">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="articles" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="article"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="article">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="topics" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="topic">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
										<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									
									<xs:attribute name="id" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ==== -->
	<!-- Page -->
	<!-- ==== -->
	
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="body" type="content-container-type"/>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="xhtml-page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="head" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:any processContents="lax"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="body" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:any processContents="lax"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ======= -->
	<!-- Content -->
	<!-- ======= -->
	
	<xs:element name="ref">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="simple-content-container-type">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="external-ref">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="simple-content-container-type">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="image">
		<xs:complexType>
			<xs:attribute name="href" type="xs:string" use="required"/>
			<xs:attribute name="alt" type="xs:string" use="required"/>
			<xs:attribute name="width" type="xs:string"/>
			<xs:attribute name="height" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Types -->
	<!-- ===== -->
	
	<xs:complexType name="code">
		<xs:complexContent>
			<xs:extension base="plain-content-container-type">
				<xs:attribute name="language">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="objective-c"/>
							<xs:enumeration value="java"/>
							<xs:enumeration value="android"/>
							<xs:enumeration value="c#"/>
							<xs:enumeration value="javascript"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ref-list-type">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="simple-content-container-type"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="plain-content-container-type">
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="simple-content-container-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- Simple Content -->
			<xs:element name="emphasis" type="simple-content-container-type"/>
			<xs:element name="strong" type="simple-content-container-type"/>
			
			<!-- Reference -->
			<xs:element ref="ref"/>
			<xs:element ref="external-ref"/>
			
			<!-- Code -->
			<xs:element name="code" type="code" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	
	<!-- TODO: Restrict content containers based on what other containers they can
		 contain (e.g. paragraph can't contain paragraph, section/section, etc). -->
	
	<xs:complexType name="content-container-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- APIs -->
			<xs:any namespace="http://www.couchbase.com/lite/api" minOccurs="0" maxOccurs="unbounded"/>
			
			<!-- Simple Content -->
			<xs:element name="emphasis" type="simple-content-container-type"/>
			<xs:element name="strong" type="simple-content-container-type"/>
			
			<!-- Reference -->
			<xs:element ref="ref"/>
			<xs:element ref="external-ref"/>
			
			<!-- Code -->
			<xs:element name="code" type="code" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="code-block" type="code" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element name="paragraph" type="simple-content-container-type" minOccurs="0" maxOccurs="unbounded"/>
			
			<!-- List -->
			<xs:element name="ordered-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="list-item" type="content-container-type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="unordered-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="list-item" type="content-container-type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="description-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="entry">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="title" type="content-container-type"/>
									<xs:element name="description" type="content-container-type"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element name="figure" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="simple-content-container-type" minOccurs="1" maxOccurs="1"/>
						<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
					</xs:sequence>
					
					<xs:attribute name="importance" default="low">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="high"/>
								<xs:enumeration value="normal"/>
								<xs:enumeration value="low"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="note" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="content-container-type">
							<xs:attribute name="type" default="note">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="note"/>
										<xs:enumeration value="tip"/>
										<xs:enumeration value="caution"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			
			<!-- Sections -->
			<xs:element name="section" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
						<xs:element name="body" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:complexContent mixed="true">
									<xs:extension base="content-container-type">
										<xs:sequence>
											<xs:element name="subsection" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
														<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					
					<xs:attribute name="id" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			
			<!-- Table -->
			<xs:element name="table" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="simple-content-container-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="header" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="simple-content-container-type">
																<xs:attribute name="colspan" type="xs:integer"/>
																<xs:attribute name="rowspan" type="xs:integer"/>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="body" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="content-container-type">
																<xs:attribute name="colspan" type="xs:integer"/>
																<xs:attribute name="rowspan" type="xs:integer"/>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Code-Set -->
			<xs:element name="code-set" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="code-block" type="code" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== Alexey1406/couchbase-mobile-portal/docs/src/guides/sync-gateway/rest-api/admin-rest-api/guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<guide xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../../../docs.xsd"
       id="sync-gateway-admin-apis">
   <title>Admin REST API</title>
   <description>REST calls made specifically for administrative purposes.</description>
  <introduction>
      <paragraph>There are two sets of REST APIs available for the Sync Gateway. The former we address in the 
      reference guide "REST API". To interact and manage the Couchbase Server Sync Gateway, you can use the Admin APIs that are illustrated in
      this reference article.</paragraph>
   </introduction>
   <articles>
      <article id="admin-api-introduction">
         <title>Introduction</title>
		   <description>A first look at the Admin REST API.</description>
		   <introduction>
			  <paragraph>The Admin REST API is a superset of the Sync REST API with the following major extensions:</paragraph>
			  <unordered-list>
				 <list-item>The capability to view, create, and modify users and roles.</list-item>
				 <list-item>The capability to perform management tasks such as creating and deleting databases.</list-item>
				 <list-item>The capability to perform administrative tasks without authentication.  The Admin REST API operates in superuser mode—you can view and modify anything without needing a password or session cookie.</list-item>
			  </unordered-list>
			  <paragraph>By default, the Admin REST API runs on port 4985 (unless you change the <code>adminInterface</code> configuration parameter). <strong>Do not expose this port</strong>—It belongs behind your firewall. Anyone who can reach this port has free access to and control over your databases and user accounts.</paragraph>
		   </introduction>
		   
			<topics>
			  <topic id="admin-rest-api-endpoints">
				 <title>Admin REST API Endpoints</title>
				 <body>
                     <note>In the URL paths shown below, any path component prefixed with a <code>$</code> is a placeholder for a name that can vary; for example, <code>$DB</code> refers to the name of the database.</note>
   					<paragraph>
   					   <code>GET /</code> - Returns a JSON object containing information about the server.</paragraph>
  					<paragraph>
  					   <code>GET /_all_dbs</code> - Returns a list of the names of all databases.</paragraph>
 					<paragraph>
 					   <code>/_profile</code> - POST to this endpoint to enable Go CPU profiling, which can be useful for diagnosing performance problems. To start profiling, send a JSON body with a <code>file</code> property whose value is a path to write the profile to. To stop profiling, send a request without a <code>file</code> property.</paragraph>
					<paragraph>
					   <code>PUT /$DB/</code> - Configures a new database. The body of the request contains the database configuration as a JSON object ()the same as an entry in the <code>databases</code> property of a configuration file. Note that this doesn't create a Couchbase Server bucket—you need to do that before configuring the database.</paragraph>
					<paragraph>
					   <code>DELETE /$DB/</code> - Removes (forgets) a database. It doesn't delete the Couchbase Server bucket or any of its data, though, so you could bring the database back later with a PUT.</paragraph>
   					<paragraph>
   					   <code>POST /$DB/_compact</code> - Compacts a database by removing obsolete document bodies. Needs to be run occasionally.</paragraph>
   					<paragraph>
   					   <code>POST /$DB/_resync</code> - Runs every document in the database through the sync function again, as though it had just been updated. This may be necessary after changing the sync function, if the new function will result in different channel assignments and access privileges.</paragraph>
					<paragraph>
					   <code>/$DB/_role/$name</code> - represents a role. This API is very similar to <code>_user</code>.</paragraph>
					<paragraph>
					   <code>/$DB/_session</code> - POST to this endpoint to create a logon session. The request body is a JSON object containing the username in the <code>name</code> object and the duration of the session (in seconds) in the <code>ttl</code> object. The response is a JSON object with properties <code>session_id</code> (the session cookie string), <code>expires</code> (the time the session expires) and <code>cookie_name</code> (the name of the HTTP cookie to set).</paragraph>
					<paragraph>
					   <code>/$DB/_user/$name</code> - represents a user account. It supports GET, PUT, and DELETE, and you can also POST to <code>/$DB/_user/</code>. The body is a JSON object; for details see the <ref href="../../2-configuration-and-administration/authorizing-users.xml#accounts">Authentication</ref> page. The special user name <code>GUEST</code> applies to unauthenticated requests.</paragraph>
					
					<note type="tip">
						A quick way to tell whether you're talking to the Admin REST API is by sending a <code>GET /</code> request and checking whether the resulting object contains an <code>"ADMIN": true</code> property.
						<ref href="../../2-configuration-and-administration/config-options-and-command-line-tool.xml">HTTP requests logged to the console</ref> show the user name of the requester after the URL. If the request is made on the admin port, this is "(ADMIN)" instead.
			  		</note>
				 </body>
			  </topic>
		   </topics>		   
      </article>
   </articles>
</guide>

=== Alexey1406/couchbase-mobile-portal/docs/src/guides/couchbase-lite/cbl-api/database-resources/get---db-.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xi="http://www.w3.org/2001/XInclude"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../docs.xsd"
         id="get---db-">
   <title>GET /{db}</title>
   <description>TODO: Add description.</description>
   <introduction>
      <paragraph>This request retrieves information about a database.</paragraph>
   </introduction>
   <topics>
      <topic id="request">
         <title>Request</title>
         <body>
            <paragraph>
               <strong>Request headers</strong>
            </paragraph>
            <paragraph>This request does not have any required headers.</paragraph>
            <paragraph>
               <strong>Query parameters</strong>
            </paragraph>
            <paragraph>This request does not use query parameters.</paragraph>
            <paragraph>
               <strong>Message body</strong>
            </paragraph>
            <paragraph>This request does not use a message body.</paragraph>
         </body>
      </topic>
      <topic id="response">
         <title>Response</title>
         <body>
            <paragraph>
               <strong>Status codes</strong>
            </paragraph>
            <unordered-list>
               <list-item>200 OK – Request completed successfully</list-item>
               <list-item>404 Not Found – Requested database not found</list-item>
            </unordered-list>
            <paragraph>
               <strong>Response headers</strong>
            </paragraph>
            <paragraph>This response uses only standard HTTP headers.</paragraph>
            <paragraph>
               <strong>Message body</strong>
            </paragraph>
            <paragraph>The message body is a JSON document that contains the following objects:</paragraph>
            <paragraph>| Name | Type |Description |</paragraph>
         </body>
      </topic>
   </topics>
</article>
