=== Alexey1406/couchbase-mobile-portal/docs/src/docs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- === -->
	<!-- Set -->
	<!-- === -->
	
	<xs:element name="set">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="0" maxOccurs="1"/>
				
				<xs:element name="items" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="set"/>
							<xs:element ref="class"/>
							<xs:element ref="guide"/>
							<xs:element ref="page"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Class -->
	<!-- ===== -->
	
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="dependencies" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="lessons" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="lesson"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lesson">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="tasks" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="task">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
										<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									
									<xs:attribute name="id" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Guide -->
	<!-- ===== -->
	
	<xs:element name="guide">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="articles" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="article"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="article">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="topics" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="topic">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
										<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									
									<xs:attribute name="id" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ==== -->
	<!-- Page -->
	<!-- ==== -->
	
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="body" type="content-container-type"/>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="xhtml-page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="head" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:any processContents="lax"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="body" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:any processContents="lax"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ======= -->
	<!-- Content -->
	<!-- ======= -->
	
	<xs:element name="ref">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="simple-content-container-type">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="external-ref">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="simple-content-container-type">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="image">
		<xs:complexType>
			<xs:attribute name="href" type="xs:string" use="required"/>
			<xs:attribute name="alt" type="xs:string" use="required"/>
			<xs:attribute name="width" type="xs:string"/>
			<xs:attribute name="height" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Types -->
	<!-- ===== -->
	
	<xs:complexType name="code">
		<xs:complexContent>
			<xs:extension base="plain-content-container-type">
				<xs:attribute name="language">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="objective-c"/>
							<xs:enumeration value="java"/>
							<xs:enumeration value="android"/>
							<xs:enumeration value="c#"/>
							<xs:enumeration value="javascript"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ref-list-type">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="simple-content-container-type"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="plain-content-container-type">
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="simple-content-container-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- Simple Content -->
			<xs:element name="emphasis" type="simple-content-container-type"/>
			<xs:element name="strong" type="simple-content-container-type"/>
			
			<!-- Reference -->
			<xs:element ref="ref"/>
			<xs:element ref="external-ref"/>
			
			<!-- Code -->
			<xs:element name="code" type="code" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	
	<!-- TODO: Restrict content containers based on what other containers they can
		 contain (e.g. paragraph can't contain paragraph, section/section, etc). -->
	
	<xs:complexType name="content-container-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- APIs -->
			<xs:any namespace="http://www.couchbase.com/lite/api" minOccurs="0" maxOccurs="unbounded"/>
			
			<!-- Simple Content -->
			<xs:element name="emphasis" type="simple-content-container-type"/>
			<xs:element name="strong" type="simple-content-container-type"/>
			
			<!-- Reference -->
			<xs:element ref="ref"/>
			<xs:element ref="external-ref"/>
			
			<!-- Code -->
			<xs:element name="code" type="code" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="code-block" type="code" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element name="paragraph" type="simple-content-container-type" minOccurs="0" maxOccurs="unbounded"/>
			
			<!-- List -->
			<xs:element name="ordered-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="list-item" type="content-container-type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="unordered-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="list-item" type="content-container-type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="description-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="entry">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="title" type="content-container-type"/>
									<xs:element name="description" type="content-container-type"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element name="figure" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="simple-content-container-type" minOccurs="1" maxOccurs="1"/>
						<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
					</xs:sequence>
					
					<xs:attribute name="importance" default="low">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="high"/>
								<xs:enumeration value="normal"/>
								<xs:enumeration value="low"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="note" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="content-container-type">
							<xs:attribute name="type" default="note">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="note"/>
										<xs:enumeration value="tip"/>
										<xs:enumeration value="caution"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			
			<!-- Sections -->
			<xs:element name="section" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
						<xs:element name="body" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:complexContent mixed="true">
									<xs:extension base="content-container-type">
										<xs:sequence>
											<xs:element name="subsection" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
														<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					
					<xs:attribute name="id" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			
			<!-- Table -->
			<xs:element name="table" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="simple-content-container-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="header" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="simple-content-container-type">
																<xs:attribute name="colspan" type="xs:integer"/>
																<xs:attribute name="rowspan" type="xs:integer"/>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="body" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="content-container-type">
																<xs:attribute name="colspan" type="xs:integer"/>
																<xs:attribute name="rowspan" type="xs:integer"/>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Code-Set -->
			<xs:element name="code-set" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="code-block" type="code" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== Alexey1406/couchbase-mobile-portal/docs/src/guides/couchbase-lite/cbl-api/introduction/notation-conventions.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xi="http://www.w3.org/2001/XInclude"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../docs.xsd"
         id="notation-conventions">
   <title>Notation Conventions</title>
   <description>TODO: Add description.</description>
   <introduction>
      <paragraph>Within the paths of the URIs presented in this reference manual:</paragraph>
      <unordered-list>
         <list-item>
            <paragraph>Path segments that start with an underscore character are static components of the URI that you use exactly as given. For example: <code>_replicate</code>.</paragraph>
         </list-item>
         <list-item>
            <paragraph>Path segments that are not preceded by an underscore character represent variables that you replace with your own value. These variables are usually enclosed in brackets as a reminder. For example: <code>{db}</code> or <code>&lt;db&gt;</code>.</paragraph>
         </list-item>
      </unordered-list>
      <paragraph>For example, suppose you have a database named cookbook. In the database, the IDs for recipes start with the string "recipe" and IDs for design documents start with the string "ddoc". The following table shows examples of values you might use for the URI path in the request that you send to the database:</paragraph>
      <table>
         <header>
            <row>
               <entry>Path</entry>
               <entry>Sample value</entry>
            </row>
         </header>
         <body>
            <row>
               <entry>
                  <code>/&lt;db&gt;</code>
               </entry>
               <entry>
                  <code>/cookbook</code>
               </entry>
            </row>
            <row>
               <entry>
                  <code>/&lt;db&gt;/_changes</code>
               </entry>
               <entry>
                  <code>/cookbook/_changes</code>
               </entry>
            </row>
            <row>
               <entry>
                  <code>/&lt;db&gt;/&lt;doc&gt;</code>
               </entry>
               <entry>
                  <code>/cookbook/recipe123</code>
               </entry>
            </row>
            <row>
               <entry>
                  <code>/&lt;db&gt;/_design/&lt;design-doc&gt;</code>
               </entry>
               <entry>
                  <code>/cookbook/_design/ddoc456</code>
               </entry>
            </row>
            <row>
               <entry>
                  <code>/_replicate</code>
               </entry>
               <entry>
                  <code>/_replicate</code>
               </entry>
            </row>
         </body>
      </table>
   </introduction>
</article>

=== Alexey1406/couchbase-mobile-portal/docs/src-orig/guides/couchbase-lite/cbl-api/local-document-resources/guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<guide xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../../../docs.xsd"
       id="local-document-resources">
   <title>Local Document Resources</title>
   <description>TODO: Add description.</description>
   <introduction>
      <paragraph>Local document resources enable you to create documents that are not replicated to other databases. You can use local documents to store configuration or other information that pertains only to the local database. The following table lists the local document resources:</paragraph>
      <table>
         <header>
            <row>
               <entry>HTTP method</entry>
               <entry>URI pattern</entry>
               <entry>Description</entry>
            </row>
         </header>
         <body>
            <row>
               <entry>
                  <code>PUT</code>
               </entry>
               <entry>
                  <code>/{db}/_local/{local-doc}</code>
               </entry>
               <entry>Creates a local document</entry>
            </row>
            <row>
               <entry>
                  <code>GET</code>
               </entry>
               <entry>
                  <code>/{db}/_local/{localdoc}</code>
               </entry>
               <entry>Retrieves a local document</entry>
            </row>
            <row>
               <entry>
                  <code>DELETE</code>
               </entry>
               <entry>
                  <code>/{db}/local/{local-doc}</code>
               </entry>
               <entry>Deletes a local document</entry>
            </row>
         </body>
      </table>
   </introduction>
   <articles>
      <xi:include href="put---db--local--local-doc-.xml"/>
      <xi:include href="get---db--local--local-doc-.xml"/>
      <xi:include href="delete---db--local--local-doc-.xml"/>
   </articles>
</guide>

=== Alexey1406/couchbase-mobile-portal/docs/src/guides/couchbase-lite/cbl-android/cbl-android-1.0b2/adding-couchbase-lite-to-your-project/adding-source-files-to-your-project.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xi="http://www.w3.org/2001/XInclude"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../../docs.xsd"
         id="adding-source-files-to-your-project">
   <title>Adding Source Files to Your Project</title>
   <description>TODO: Add description.</description>
   <introduction>
      <paragraph>If you need to debug Couchbase Lite, you can include the Couchbase Lite code in your project rather than using a JAR file or the Maven artifact dependencies. If you choose to add the source files, make sure you remove any Maven or JAR file dependencies that you used previously.</paragraph>
      <paragraph>Follow these steps to add Couchbase Lite source files directly to your project:</paragraph>
   </introduction>
   <topics>
      <topic id="add-submodules">
         <title>Add submodules</title>
         <body>
            <ordered-list>
               <list-item>
                  <paragraph>Change to the parent <strong>MyProject</strong> directory, which contains the <strong>settings.gradle</strong> file.</paragraph>

                  <code-block>
$ cd MyProject 
</code-block>
               </list-item>
               <list-item>
                  <paragraph>Add the required submodule:</paragraph>

                  <code-block>
$ git submodule add https://github.com/couchbase/couchbase-lite-android-core.git CBLite
</code-block>
               </list-item>
               <list-item>
                  <paragraph>Add any optional submodules that you need:</paragraph>

                  <code-block>
$ git submodule add https://github.com/couchbase/couchbase-lite-android-listener.git CBLiteListener
$ git submodule add https://github.com/couchbase/couchbase-lite-android-javascript.git CBLiteJavascript
</code-block>
               </list-item>
            </ordered-list>
         </body>
      </topic>
      <topic id="update-gradle-files">
         <title>Update Gradle files</title>
         <body>
            <ordered-list>
               <list-item>
                  <paragraph>Add the following line to the <strong>settings.gradle</strong> file:</paragraph>

                  <code-block>
include ':MyProject', ':CBLite'
</code-block>
               </list-item>
               <list-item>
                  <paragraph>If you included any optional submodules, add include statements for them to the <strong>settings.gradle</strong> file.</paragraph>
               </list-item>
               <list-item>
                  <paragraph>Add the following dependency to the <strong>MyProject/MyProject/build.gradle</strong> file:</paragraph>

                  <code-block>
dependencies {
    ... existing dependencies ...
    compile project(':CBLite')
</code-block>

                  <paragraph>}</paragraph>
               </list-item>
               <list-item>
                  <paragraph>If you included any optional submodules, add compile statements for them to the <strong>MyProject/MyProject/build.gradle</strong> file.</paragraph>
               </list-item>
            </ordered-list>
         </body>
      </topic>
   </topics>
</article>
