=== Alexey1406/couchbase-mobile-portal/docs/src/docs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- === -->
	<!-- Set -->
	<!-- === -->
	
	<xs:element name="set">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="0" maxOccurs="1"/>
				
				<xs:element name="items" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="set"/>
							<xs:element ref="class"/>
							<xs:element ref="guide"/>
							<xs:element ref="page"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Class -->
	<!-- ===== -->
	
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="dependencies" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="lessons" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="lesson"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lesson">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="tasks" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="task">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
										<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									
									<xs:attribute name="id" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Guide -->
	<!-- ===== -->
	
	<xs:element name="guide">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="articles" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element ref="article"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="article">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="related" type="ref-list-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="introduction" type="content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="topics" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="topic">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
										<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
									
									<xs:attribute name="id" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ==== -->
	<!-- Page -->
	<!-- ==== -->
	
	<xs:element name="page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="body" type="content-container-type"/>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="xhtml-page">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
				
				<xs:element name="icon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="head" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:any processContents="lax"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="body" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:any processContents="lax"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- ======= -->
	<!-- Content -->
	<!-- ======= -->
	
	<xs:element name="ref">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="simple-content-container-type">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="external-ref">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="simple-content-container-type">
					<xs:attribute name="href" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="image">
		<xs:complexType>
			<xs:attribute name="href" type="xs:string" use="required"/>
			<xs:attribute name="alt" type="xs:string" use="required"/>
			<xs:attribute name="width" type="xs:string"/>
			<xs:attribute name="height" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<!-- ===== -->
	<!-- Types -->
	<!-- ===== -->
	
	<xs:complexType name="code">
		<xs:complexContent>
			<xs:extension base="plain-content-container-type">
				<xs:attribute name="language">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="objective-c"/>
							<xs:enumeration value="java"/>
							<xs:enumeration value="android"/>
							<xs:enumeration value="c#"/>
							<xs:enumeration value="javascript"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ref-list-type">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="simple-content-container-type"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="plain-content-container-type">
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="simple-content-container-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- Simple Content -->
			<xs:element name="emphasis" type="simple-content-container-type"/>
			<xs:element name="strong" type="simple-content-container-type"/>
			
			<!-- Reference -->
			<xs:element ref="ref"/>
			<xs:element ref="external-ref"/>
			
			<!-- Code -->
			<xs:element name="code" type="code" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	
	<!-- TODO: Restrict content containers based on what other containers they can
		 contain (e.g. paragraph can't contain paragraph, section/section, etc). -->
	
	<xs:complexType name="content-container-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<!-- APIs -->
			<xs:any namespace="http://www.couchbase.com/lite/api" minOccurs="0" maxOccurs="unbounded"/>
			
			<!-- Simple Content -->
			<xs:element name="emphasis" type="simple-content-container-type"/>
			<xs:element name="strong" type="simple-content-container-type"/>
			
			<!-- Reference -->
			<xs:element ref="ref"/>
			<xs:element ref="external-ref"/>
			
			<!-- Code -->
			<xs:element name="code" type="code" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="code-block" type="code" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element name="paragraph" type="simple-content-container-type" minOccurs="0" maxOccurs="unbounded"/>
			
			<!-- List -->
			<xs:element name="ordered-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="list-item" type="content-container-type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="unordered-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="list-item" type="content-container-type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="description-list" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="entry">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="title" type="content-container-type"/>
									<xs:element name="description" type="content-container-type"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element name="figure" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="simple-content-container-type" minOccurs="1" maxOccurs="1"/>
						<xs:element ref="image" minOccurs="1" maxOccurs="1"/>
					</xs:sequence>
					
					<xs:attribute name="importance" default="low">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="high"/>
								<xs:enumeration value="normal"/>
								<xs:enumeration value="low"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="note" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="content-container-type">
							<xs:attribute name="type" default="note">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="note"/>
										<xs:enumeration value="tip"/>
										<xs:enumeration value="caution"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			
			<!-- Sections -->
			<xs:element name="section" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
						<xs:element name="body" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:complexContent mixed="true">
									<xs:extension base="content-container-type">
										<xs:sequence>
											<xs:element name="subsection" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="title" type="plain-content-container-type" minOccurs="1" maxOccurs="1"/>
														<xs:element name="body" type="content-container-type" minOccurs="1" maxOccurs="1"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					
					<xs:attribute name="id" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			
			<!-- Table -->
			<xs:element name="table" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="description" type="simple-content-container-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="header" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="simple-content-container-type">
																<xs:attribute name="colspan" type="xs:integer"/>
																<xs:attribute name="rowspan" type="xs:integer"/>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="body" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="content-container-type">
																<xs:attribute name="colspan" type="xs:integer"/>
																<xs:attribute name="rowspan" type="xs:integer"/>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Code-Set -->
			<xs:element name="code-set" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="code-block" type="code" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== Alexey1406/couchbase-mobile-portal/docs/src/guides/couchbase-lite/cbl-ios/release-notes/1-0-beta-2--december-2013-.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xi="http://www.w3.org/2001/XInclude"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../docs.xsd"
         id="1-0-beta-2--december-2013-">
   <title>1.0 Beta 2 (December 2013)</title>
   <description>TODO: Add description.</description>
   <introduction>
      <paragraph>This is the second Beta release of Couchbase Lite iOS 1.0. Couchbase Lite is an ultra-lightweight, reliable, secure JSON database built for all your online and offline mobile application needs. The 1.0 version features native APIs, REST APIs, JSON support, and sync capability. The beta release is available to all community-edition customers.</paragraph>
   </introduction>
   <topics>
      <topic id="features">
         <title>Features</title>
         <body>
            <unordered-list>
               <list-item>
                  <strong>Replication enhancements</strong>—The replicator can now sync specific sets of documents, and pull replications can now optionally poll. Replications run on a separate background thread so they won't block the main thread or regular Couchbase Lite operations (except unavoidably while writing to the database).</list-item>
               <list-item>
                  <strong>Revision management enhancements</strong>—Database compaction now prunes the oldest revisions after a document's revision history grows beyond a maximum length.</list-item>
               <list-item>
                  <strong>CBLModel enhancements</strong>—CBLModel now supports all remaining scalar property types and custom object classes as properties.</list-item>
               <list-item>
                  <strong>Performance enhancements</strong>—A number of performance enhancements were added, including tuning of the <code>CBLBatcher</code> class, incremental parsing of the <code>_changes</code> feed, and significant speeds to SQLite database access. </list-item>
               <list-item>
                  <strong>API name changes</strong>—API names changed to follow a language-neutral API spec in preparation to make development for other platforms simple and consistent.</list-item>
               <list-item>
                  <strong>Flexible concurrency</strong>—Made concurrency more flexible by allowing Couchbase Lite to run on a dispatch queue and adding a way to call it from any thread.</list-item>
               <list-item>Support for 64-bit iOS apps.</list-item>
            </unordered-list>
         </body>
      </topic>
      <topic id="fixes-in-beta-2">
         <title>Fixes in Beta 2</title>
         <body>
            <unordered-list>
               <list-item>
                  <paragraph>Indexing and Querying for JSON</paragraph>

                  <unordered-list>
                     <list-item>The <code>CBLQueryRow</code> class equality test now compares sequence numbers if emitted values are nil or reflect no change.</list-item>
                     <list-item>During database compaction, excessively-deep revision trees have their oldest revisions removed entirely. The depth limit can be configured.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/115"/>, <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/118"/>
                  </paragraph>
               </list-item>
               <list-item>
                  <paragraph>Replication</paragraph>

                  <unordered-list>
                     <list-item>The property <code>docs_id</code> is now supported.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/102"/>
                  </paragraph>
               </list-item>
            </unordered-list>
         </body>
      </topic>
      <topic id="known-issues">
         <title>Known Issues</title>
         <body>
            <unordered-list>
               <list-item>
                  <paragraph>API names in Beta 2</paragraph>

                  <unordered-list>
                     <list-item>As mentioned in the Beta 2 feature list, we've made API changes to support a language-neutral spec. In Beta 2 the old method and property names are still available, but marked as deprecated. Xcode issues warnings for these, and the warning messages tell you what name to use instead.</list-item>
                  </unordered-list>
               </list-item>
               <list-item>
                  <paragraph>Indexing and querying for JSON</paragraph>

                  <unordered-list>
                     <list-item>Working on a JavaScript equivalent of the CouchDB MapReduce sum() function, which adds up the numeric values of all arguments.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/75"/>, <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/76"/>
                  </paragraph>

                  <unordered-list>
                     <list-item>The querying parameter startkey_docid is not yet implemented.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/111"/>
                  </paragraph>
               </list-item>
               <list-item>
                  <paragraph>Third-party Compatibility</paragraph>

                  <unordered-list>
                     <list-item>We do not recommend using Couchbase Lite with the Dropbox Sync SDK at the same time in development.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/199"/>
                  </paragraph>

                  <unordered-list>
                     <list-item>Server header modification is required when attempting to use <code>_bulk_get</code> with a reverse proxy.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/215"/>
                  </paragraph>
               </list-item>
               <list-item>
                  <paragraph>Sync Gateway support</paragraph>

                  <unordered-list>
                     <list-item>To share a cookie with an application, you need to set the path option in the cookie header with <code>Path=/</code>.</list-item>
                  </unordered-list>
                  <paragraph>Issues: <external-ref href="https://github.com/couchbase/couchbase-lite-ios/issues/212"/>
                  </paragraph>
               </list-item>
            </unordered-list>
         </body>
      </topic>
   </topics>
</article>

=== Alexey1406/couchbase-mobile-portal/docs/src/guides/couchbase-lite/cbl-ios/troubleshooting/logging.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xi="http://www.w3.org/2001/XInclude"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../docs.xsd"
         id="logging">
   <title>Logging</title>
   <description>TODO: Add description.</description>
   <introduction>
      <paragraph>Couchbase Lite includes some logging messages that you can enable for troubleshooting purposes. Serious and unexpected problems are always logged with a message that starts with the text "WARNING:", but logging for serious problems needs to be enabled via the user defaults system or command-line arguments.</paragraph>
   </introduction>
   <topics>
      <topic id="the-logging-api">
         <title>The Logging API</title>
         <body>
            <paragraph>Couchbase Lite uses the logging API from my MYUtilities library. There's a <code>Log(@"...")</code> function that's used just like <code>NSLog</code>. It produces no output by default, but there's a master switch to turn it on (the boolean user default also called <code>Log</code>.) </paragraph>
            <paragraph>Beyond that, the <code>LogTo(Channel, @"...")</code> function logs to an arbitrary named "channel". Channels are off by default but are individually enabled by user defaults. For example, the default <code>LogFoo</code> turns on the <code>Foo</code> channel (but only if the master log switch is enabled too.</paragraph>
         </body>
      </topic>
      <topic id="enabling-logging">
         <title>Enabling Logging</title>
         <body>
            <paragraph>You can turn these flags on programmatically with the <code>NSUserDefaults</code> class, or persistently from the command-line using the <code>defaults</code> tool (using your app's bundle ID, of course). During development, the most convenient way is to set them from Xcode's scheme editor. This lets you toggle them with GUI checkboxes. Here's how:</paragraph>
            <ordered-list>
               <list-item>Pull down the scheme menu in the toolbar and choose "Edit Scheme..."</list-item>
               <list-item>Choose "Run" from the source list on the left side of the sheet.</list-item>
               <list-item>Choose the "Arguments" tab.</list-item>
               <list-item>Click the "+" button at the bottom of the "Arguments Passed On Launch" list.</list-item>
               <list-item>In the new list item that appears, type <code>-Log YES</code>.</list-item>
            </ordered-list>
            <paragraph>This adds two command-line arguments when Xcode launches your app. An <code>NSUserDefaults</code> object parses these at launch time and temporarily sets the value of <code>Log</code> to <code>YES</code> (aka <code>true</code>.) This is persistent as long as you run your app from Xcode, but it's not stored in the system or device user defaults so it has no effect on launching your app normally. Moreover, you can easily turn it off by using the checkbox next to its list item.</paragraph>
            <paragraph>Enabling "channels" works the same way. Add another argument item whose value is, for example, <code>-LogFoo YES</code> to turn on channel <code>Foo</code>. (Remember that you also need to have the <code>-Log YES</code> item enabled or no logs will appear at all.)</paragraph>
            <image href="images/logging.png"/>
         </body>
      </topic>
      <topic id="useful-logging-channels">
         <title>Useful Logging Channels</title>
         <body>
            <paragraph>Most of Couchbase Lite's logging goes to specific channels. Here are some useful ones to turn on:</paragraph>
            <unordered-list>
               <list-item>
                  <strong>Sync</strong> — High-level status of sync/replication.</list-item>
               <list-item>
                  <strong>SyncVerbose</strong> — More detailed info about sync/replication.</list-item>
               <list-item>
                  <strong>RemoteRequest</strong> — The individual HTTP requests the replicator sends to the remote server.</list-item>
               <list-item>
                  <strong>View</strong> — View indexing and queries.</list-item>
               <list-item>
                  <strong>ChangeTracker</strong> — The <code>_changes</code> feed listener.</list-item>
               <list-item>
                  <strong>CBLRouter</strong> — If using the REST API, this logs info about the URL requests being handled.</list-item>
            </unordered-list>
         </body>
      </topic>
   </topics>
</article>
